// Embeds src/pages/*.html into src/pages/generated.ts so the server (and the Vercel
// bundle) ships the pages as code rather than reading files at runtime.
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const dir = path.resolve('src/pages');
const files = (await readdir(dir)).filter((f) => f.endsWith('.html')).sort();
const entries = [];
for (const f of files) {
  const key = path.basename(f, '.html');
  const html = await readFile(path.join(dir, f), 'utf8');
  entries.push(`  ${JSON.stringify(key)}: ${JSON.stringify(html)},`);
}
// Scripts and the shared stylesheet the pages load (src/pages/scripts/*.js, src/pages/styles/*.css),
// served at /dashboard/assets/<name>.
const scriptFiles = [];
const scripts = [];
for (const [sub, ext] of [['scripts', '.js'], ['styles', '.css']]) {
  const d = path.join(dir, sub);
  for (const f of (await readdir(d).catch(() => [])).filter((x) => x.endsWith(ext)).sort()) {
    scriptFiles.push(f);
    scripts.push(`  ${JSON.stringify(f)}: ${JSON.stringify(await readFile(path.join(d, f), 'utf8'))},`);
  }
}
// Brand assets (src/pages/assets/*): the logo, the favicon and the touch icon, served from the site root.
const assetDir = path.join(dir, 'assets');
const assetTypes = { '.svg': 'image/svg+xml', '.png': 'image/png', '.ico': 'image/x-icon' };
const assetFiles = (await readdir(assetDir).catch(() => [])).filter((f) => path.extname(f) in assetTypes).sort();
const assets = [];
for (const f of assetFiles) {
  const base64 = (await readFile(path.join(assetDir, f))).toString('base64');
  assets.push(`  ${JSON.stringify(f)}: { type: ${JSON.stringify(assetTypes[path.extname(f)])}, base64: ${JSON.stringify(base64)} },`);
}
const out = `// GENERATED by scripts/embed-pages.mjs from src/pages/*.html, src/pages/scripts/*.js, src/pages/styles/*.css and src/pages/assets/* — do not edit by hand.
export const PAGES: Record<${files.map((f) => JSON.stringify(path.basename(f, '.html'))).join(' | ') || 'string'}, string> = {
${entries.join('\n')}
};

export const SCRIPTS: Record<string, string> = {
${scripts.join('\n')}
};

export const ASSETS: Record<string, { type: string; base64: string }> = {
${assets.join('\n')}
};
`;
await writeFile(path.join(dir, 'generated.ts'), out);
console.log(`embedded ${files.length} page(s): ${files.map((f) => path.basename(f, '.html')).join(', ')}; ${scriptFiles.length} script(s): ${scriptFiles.join(', ')}; ${assetFiles.length} asset(s): ${assetFiles.join(', ')}`);
