// Embeds src/pages/*.html into src/pages/generated.ts so the server (and the Vercel
// bundle) ships the pages as code rather than reading files at runtime.
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const dir = path.resolve('src/pages');
const files = (await readdir(dir)).filter((f) => f.endsWith('.html')).sort();
const entries = [];
for (const f of files) {
  const key = path.basename(f, '.html');
  const html = await readFile(path.join(dir, f), 'utf8');
  entries.push(`  ${JSON.stringify(key)}: ${JSON.stringify(html)},`);
}
const out = `// GENERATED by scripts/embed-pages.mjs from src/pages/*.html — do not edit by hand.
export const PAGES: Record<${files.map((f) => JSON.stringify(path.basename(f, '.html'))).join(' | ') || 'string'}, string> = {
${entries.join('\n')}
};
`;
await writeFile(path.join(dir, 'generated.ts'), out);
console.log(`embedded ${files.length} page(s): ${files.map((f) => path.basename(f, '.html')).join(', ')}`);
