// Embeds src/pages/*.html into src/pages/generated.ts so the server (and the Vercel
// bundle) ships the pages as code rather than reading files at runtime.
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const dir = path.resolve('src/pages');
const files = (await readdir(dir)).filter((f) => f.endsWith('.html')).sort();
const entries = [];
for (const f of files) {
  const key = path.basename(f, '.html');
  const html = await readFile(path.join(dir, f), 'utf8');
  entries.push(`  ${JSON.stringify(key)}: ${JSON.stringify(html)},`);
}
// Scripts the pages load (src/pages/scripts/*.js), served at /dashboard/assets/<name>.js.
const scriptDir = path.join(dir, 'scripts');
const scriptFiles = (await readdir(scriptDir).catch(() => [])).filter((f) => f.endsWith('.js')).sort();
const scripts = [];
for (const f of scriptFiles) {
  scripts.push(`  ${JSON.stringify(f)}: ${JSON.stringify(await readFile(path.join(scriptDir, f), 'utf8'))},`);
}
const out = `// GENERATED by scripts/embed-pages.mjs from src/pages/*.html and src/pages/scripts/*.js — do not edit by hand.
export const PAGES: Record<${files.map((f) => JSON.stringify(path.basename(f, '.html'))).join(' | ') || 'string'}, string> = {
${entries.join('\n')}
};

export const SCRIPTS: Record<string, string> = {
${scripts.join('\n')}
};
`;
await writeFile(path.join(dir, 'generated.ts'), out);
console.log(`embedded ${files.length} page(s): ${files.map((f) => path.basename(f, '.html')).join(', ')}; ${scriptFiles.length} script(s): ${scriptFiles.join(', ')}`);
